import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import PostList from '../../components/PostList';
import Head from 'next/head';
import Header from '../../components/Header';
import Footer from '../../components/Footer';
export default function BlogPage({ posts }) {
  return (
    <>
      <Head>
        <title>Blog Posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <PostList posts={posts} />
      <Footer absolute={false} />
    </>
  );
}

export async function getStaticProps() {
  // Get files from posts directory
  const files = fs.readdirSync(path.join('posts'));

  // Get slug and frontmatter from posts
  const posts = files.map((filename) => {
    // Create slug
    const slug = filename.replace('.md', '');

    // Get frontmatter
    const markdownWithMeta = fs.readFileSync(path.join('posts', filename), 'utf-8');
    // Renames data to frontmatter
    const { data: frontmatter } = matter(markdownWithMeta);
    return {
      slug,
      frontmatter,
    };
  });
  return {
    props: {
      posts: posts,
    },
  };
}
